package com.apiflow.service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.springframework.stereotype.Service;

import com.apiflow.model.ApiRequest;
import com.apiflow.model.Environment;
import com.apiflow.model.Folder;
import com.apiflow.model.KeyValue;
import com.apiflow.model.RequestCollection;
import com.apiflow.store.FileStore;

@Service
public class DocsService {

	private final FileStore store;

	public DocsService(FileStore store) {
		this.store = store;
	}

	public String autoGenerateDocs(RequestCollection collection) {
		StringBuilder docs = new StringBuilder();
		docs.append("# ").append(collection.getName()).append("\n\n");
		docs.append("Auto-generated from ").append(collection.getRequests().size()).append(" requests.\n\n");
		if (collection.getDocs() != null && !collection.getDocs().isBlank()) {
			docs.append(collection.getDocs()).append("\n\n");
		}
		for (Folder folder : collection.getFolders()) {
			docs.append("## ").append(folder.getName()).append("\n");
			if (folder.getDocs() != null && !folder.getDocs().isBlank()) {
				docs.append(folder.getDocs()).append("\n");
			}
			for (ApiRequest request : collection.getRequests()) {
				if (folder.getId().equals(request.getFolderId())) {
					appendRequestDoc(docs, request);
				}
			}
			docs.append("\n");
		}
		for (ApiRequest request : collection.getRequests()) {
			if (request.getFolderId() == null || request.getFolderId().isBlank()) {
				appendRequestDoc(docs, request);
			}
		}
		return docs.toString().trim();
	}

	private void appendRequestDoc(StringBuilder docs, ApiRequest request) {
		docs.append("### ").append(request.getName()).append("\n");
		docs.append("- **Method:** `").append(request.getMethod()).append("`\n");
		docs.append("- **URL:** `").append(request.getUrl()).append("`\n");
		if (request.getDocs() != null && !request.getDocs().isBlank()) {
			docs.append("\n").append(request.getDocs()).append("\n");
		}
		if (!request.getParams().isEmpty()) {
			docs.append("\n**Query params:**\n");
			for (KeyValue param : request.getParams()) {
				if (param.isEnabled()) {
					docs.append("- `").append(param.getKey()).append("` — ").append(param.getValue()).append("\n");
				}
			}
		}
		docs.append("\n");
	}

	public DeployResult deploy(RequestCollection collection, List<Environment> environments) {
		String html = html(collection, environments);
		Path dir = store.root().resolve("docs").resolve(collection.getId());
		try {
			Files.createDirectories(dir);
			Path file = dir.resolve("index.html");
			Files.writeString(file, html, StandardCharsets.UTF_8);
			Path readme = dir.resolve("README.txt");
			Files.writeString(readme, """
				ApiFlow static documentation bundle

				Open index.html in a browser, or host this folder on any static file host
				(GitHub Pages, Netlify, S3, etc.).

				Local preview while ApiFlow is running:
				http://localhost:8080/api/docs/%s
				""".formatted(collection.getId()), StandardCharsets.UTF_8);
			return new DeployResult(true, "/api/docs/" + collection.getId(), file.toString(), collection.getName());
		}
		catch (IOException ex) {
			throw new IllegalArgumentException("Could not deploy docs");
		}
	}

	public byte[] exportStaticBundle(RequestCollection collection, List<Environment> environments) {
		String html = html(collection, environments);
		String readme = """
			ApiFlow static documentation bundle

			Upload this zip to any static host (GitHub Pages, Netlify, Cloudflare Pages, S3).
			The entry point is index.html.
			""";
		try (ByteArrayOutputStream bytes = new ByteArrayOutputStream(); ZipOutputStream zip = new ZipOutputStream(bytes)) {
			writeZipEntry(zip, "index.html", html);
			writeZipEntry(zip, "README.txt", readme);
			zip.finish();
			return bytes.toByteArray();
		}
		catch (IOException ex) {
			throw new IllegalArgumentException("Could not export docs bundle");
		}
	}

	private static void writeZipEntry(ZipOutputStream zip, String name, String content) throws IOException {
		zip.putNextEntry(new ZipEntry(name));
		zip.write(content.getBytes(StandardCharsets.UTF_8));
		zip.closeEntry();
	}

	public String readDeployed(String collectionId) {
		Path file = store.root().resolve("docs").resolve(collectionId).resolve("index.html");
		if (!Files.exists(file)) {
			throw new NotFoundException("Deployed docs not found");
		}
		try {
			return Files.readString(file, StandardCharsets.UTF_8);
		}
		catch (IOException ex) {
			throw new IllegalArgumentException("Could not read deployed docs");
		}
	}

	public String html(RequestCollection collection) {
		return html(collection, List.of());
	}

	public String html(RequestCollection collection, List<Environment> environments) {
		return html(collection, environments, false);
	}

	public String html(RequestCollection collection, List<Environment> environments, boolean useProxy) {
		String docsText = collection.getDocs();
		if (docsText == null || docsText.isBlank()) {
			docsText = autoGenerateDocs(collection);
		}
		StringBuilder html = new StringBuilder();
		html.append("<!doctype html><html><head><meta charset=\"utf-8\"><title>").append(escape(collection.getName())).append("</title>");
		html.append("<style>")
			.append("body{font-family:system-ui,sans-serif;margin:0;background:#0f1117;color:#e8eaed}")
			.append(".wrap{max-width:1080px;margin:0 auto;padding:24px}")
			.append("header{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:20px}")
			.append("select,input,textarea{padding:8px 10px;border-radius:8px;border:1px solid #3c4043;background:#202124;color:inherit;font:inherit}")
			.append("input{flex:1;min-width:220px}")
			.append("textarea{width:100%;min-height:72px}")
			.append("section{border:1px solid #3c4043;border-radius:12px;padding:16px;margin:16px 0;background:#171923}")
			.append("code,pre{background:#0b0d12;border-radius:8px}")
			.append("pre{padding:12px;overflow:auto;white-space:pre-wrap}")
			.append(".samples{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}")
			.append(".playground{margin-top:12px;padding:12px;border:1px dashed #5f6368;border-radius:8px;display:grid;gap:8px}")
			.append(".play-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}")
			.append("button{padding:8px 12px;border-radius:8px;border:0;background:#4c8bf5;color:white;cursor:pointer}")
			.append(".muted{color:#9aa0a6}")
			.append(".badge{font-size:12px;padding:2px 8px;border-radius:999px;background:#303134}")
			.append("</style></head><body><div class=\"wrap\">");
		html.append("<header><h1 style=\"margin:0\">").append(escape(collection.getName())).append("</h1>");
		html.append("<span class=\"badge\">Interactive docs</span>");
		if (!environments.isEmpty()) {
			html.append("<label>Environment<select id=\"envSelect\">");
			html.append("<option value=\"\">None</option>");
			for (Environment environment : environments) {
				html.append("<option value=\"").append(escape(environment.getId())).append("\">")
					.append(escape(environment.getName())).append("</option>");
			}
			html.append("</select></label>");
		}
		html.append("<input id=\"search\" placeholder=\"Search requests, URLs, params…\" /></header>");
		html.append("<script>const ENV=").append(envJson(environments)).append(";</script>");
		html.append("<div class=\"muted docs-intro\">").append(escape(docsText).replace("\n", "<br>")).append("</div>");
		int index = 0;
		for (ApiRequest request : collection.getRequests()) {
			html.append(renderRequest(request, index++));
		}
		html.append("""
				<script>
				const search=document.getElementById('search');
				search?.addEventListener('input',()=>{
				  const q=search.value.toLowerCase();
				  document.querySelectorAll('[data-doc]').forEach(el=>el.style.display=el.dataset.index.includes(q)||el.innerText.toLowerCase().includes(q)?'':'none');
				});
				function interpolate(input, vars){
				  if(!input) return '';
				  return input.replace(/\\{\\{\\s*([A-Za-z0-9_.-]+)\\s*}}/g,(m,k)=>Object.prototype.hasOwnProperty.call(vars,k)?vars[k]:m);
				}
				function currentVars(){
				  const id=document.getElementById('envSelect')?.value||'';
				  return (ENV[id]||{});
				}
				function runRequest(id){
				  const el=document.getElementById(id);
				  const method=(document.getElementById(id+'-method')?.value||el.dataset.method||'GET').toUpperCase();
				  const template=document.getElementById(id+'-url')?.value||el.dataset.url;
				  const url=interpolate(template, currentVars());
				  const headersRaw=document.getElementById(id+'-headers')?.value||'{}';
				  const body=document.getElementById(id+'-body')?.value||'';
				  let headers={};
				  try{ headers=JSON.parse(headersRaw||'{}'); }catch(e){ document.getElementById(id+'-out').textContent='Invalid headers JSON'; return; }
				  const started=performance.now();
				  const write=(status,statusText,text,ms)=>{
				    document.getElementById(id+'-out').textContent=`${status} ${statusText} (${ms} ms)\\n`+(text||'').slice(0,4000);
				  };
				  if(%s){
				    fetch('http://localhost:8080/api/platform/docs/proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,url,headers,body})})
				      .then(r=>r.json()).then(r=>write(r.status||0,r.statusText||'',r.body||'',r.timeMs||Math.round(performance.now()-started)))
				      .catch(e=>document.getElementById(id+'-out').textContent=e.message);
				    return;
				  }
				  const opts={method,headers};
				  if(!['GET','HEAD'].includes(method) && body) opts.body=body;
				  fetch(url,opts).then(async r=>{
				    const text=await r.text();
				    write(r.status,r.statusText,text,Math.round(performance.now()-started));
				  }).catch(e=>document.getElementById(id+'-out').textContent=e.message);
				}
				</script>
				<p class="muted">Generated by ApiFlow · Deployed locally</p></div></body></html>
				""".formatted(useProxy));
		return html.toString();
	}

	private String renderRequest(ApiRequest request, int index) {
		String id = "req-" + index;
		String searchBlob = (request.getName() + " " + request.getUrl() + " " + request.getMethod()).toLowerCase();
		StringBuilder section = new StringBuilder();
		section.append("<section data-doc data-index=\"").append(escape(searchBlob)).append("\" id=\"").append(id).append("\" ")
			.append("data-method=\"").append(escape(request.getMethod())).append("\" data-url=\"").append(escape(request.getUrl())).append("\">");
		section.append("<h3>").append(escape(request.getName())).append(" <code>").append(escape(request.getMethod())).append("</code></h3>");
		section.append("<p><code>").append(escape(request.getUrl())).append("</code></p>");
		if (request.getDocs() != null && !request.getDocs().isBlank()) {
			section.append("<p class=\"muted\">").append(escape(request.getDocs()).replace("\n", "<br>")).append("</p>");
		}
		if (!request.getParams().isEmpty()) {
			section.append("<p><strong>Params</strong></p><ul>");
			for (KeyValue param : request.getParams()) {
				if (param.isEnabled()) {
					section.append("<li><code>").append(escape(param.getKey())).append("</code> = ").append(escape(param.getValue())).append("</li>");
				}
			}
			section.append("</ul>");
		}
		if (!request.getExamples().isEmpty()) {
			for (var example : request.getExamples()) {
				section.append("<h4>").append(escape(example.getName())).append(" (").append(example.getStatus()).append(")</h4>");
				section.append("<pre>").append(escape(example.getBody())).append("</pre>");
			}
		}
		section.append("<div class=\"samples\">");
		section.append(sampleBlock("cURL", toCurl(request)));
		section.append(sampleBlock("fetch", toFetch(request)));
		section.append(sampleBlock("Python", toPython(request)));
		section.append("</div>");
		section.append("<div class=\"playground\">");
		section.append("<strong>Playground</strong>");
		section.append("<div class=\"play-row\"><label>Method<input id=\"").append(id).append("-method\" value=\"").append(escape(request.getMethod())).append("\" size=\"8\"/></label>");
		section.append("<label style=\"flex:1\">URL<input id=\"").append(id).append("-url\" value=\"").append(escape(request.getUrl())).append("\"/></label></div>");
		section.append("<label>Headers (JSON)<textarea id=\"").append(id).append("-headers\">").append(escape(headersJson(request))).append("</textarea></label>");
		if (!"GET".equalsIgnoreCase(request.getMethod()) && !"HEAD".equalsIgnoreCase(request.getMethod())) {
			String body = "graphql".equals(request.getBodyType()) ? request.getGraphqlQuery() : request.getBody();
			section.append("<label>Body<textarea id=\"").append(id).append("-body\">").append(escape(body == null ? "" : body)).append("</textarea></label>");
		}
		section.append("<button onclick=\"runRequest('").append(id).append("')\">Send request</button>");
		section.append("<pre id=\"").append(id).append("-out\">Response appears here.</pre></div>");
		section.append("</section>");
		return section.toString();
	}

	private static String headersJson(ApiRequest request) {
		Map<String, String> headers = new LinkedHashMap<>();
		for (KeyValue header : request.getHeaders()) {
			if (header.isEnabled() && header.getKey() != null && !header.getKey().isBlank()) {
				headers.put(header.getKey(), header.getValue() == null ? "" : header.getValue());
			}
		}
		if ("graphql".equals(request.getBodyType())) {
			headers.putIfAbsent("Content-Type", "application/json");
		}
		try {
			return new tools.jackson.databind.ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(headers);
		}
		catch (Exception ex) {
			return "{}";
		}
	}

	private static String sampleBlock(String label, String code) {
		return "<div><strong>" + escape(label) + "</strong><pre>" + escape(code) + "</pre></div>";
	}

	private static String toCurl(ApiRequest request) {
		return "curl -X " + request.getMethod() + " '" + request.getUrl() + "'";
	}

	private static String toFetch(ApiRequest request) {
		return "fetch('" + request.getUrl() + "', { method: '" + request.getMethod() + "' })";
	}

	private static String toPython(ApiRequest request) {
		return "requests." + request.getMethod().toLowerCase() + "('" + request.getUrl() + "')";
	}

	private static String envJson(List<Environment> environments) {
		Map<String, Map<String, String>> payload = new LinkedHashMap<>();
		for (Environment environment : environments) {
			Map<String, String> vars = new LinkedHashMap<>();
			for (KeyValue variable : environment.getVariables()) {
				if (variable.isEnabled() && variable.getKey() != null) {
					vars.put(variable.getKey(), variable.getValue() == null ? "" : variable.getValue());
				}
			}
			payload.put(environment.getId(), vars);
		}
		try {
			return new tools.jackson.databind.ObjectMapper().writeValueAsString(payload);
		}
		catch (Exception ex) {
			return "{}";
		}
	}

	private static String escape(String value) {
		if (value == null) {
			return "";
		}
		return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
	}

	public PublishResult publishPublic(RequestCollection collection, List<Environment> environments) {
		String html = html(collection, environments, true);
		String standalone = html(collection, environments, false);
		Path dir = store.root().resolve("docs").resolve(collection.getId());
		Path publicDir = store.root().resolve("public");
		Path standaloneFile;
		try {
			Files.createDirectories(dir);
			Files.writeString(dir.resolve("index.html"), html, StandardCharsets.UTF_8);
			Files.createDirectories(publicDir);
			standaloneFile = publicDir.resolve("docs-" + collection.getId() + ".html");
			Files.writeString(standaloneFile, standalone, StandardCharsets.UTF_8);
		}
		catch (IOException ex) {
			throw new IllegalArgumentException("Could not publish docs");
		}
		String publicUrl = "/public/" + standaloneFile.getFileName();
		return new PublishResult(true, publicUrl, standaloneFile.toString(), embedButton(collection.getId()).html());
	}

	public EmbedResult embedButton(String collectionId) {
		String html = """
			<a href="/public/docs-%s.html" target="_blank" rel="noopener"
			style="display:inline-flex;align-items:center;gap:8px;padding:10px 16px;border-radius:8px;background:#ff6c37;color:white;text-decoration:none;font-family:system-ui,sans-serif;font-weight:600">
			Run in ApiFlow</a>
			""".formatted(collectionId);
		return new EmbedResult(html, "");
	}

	public String shareHtml(ShareLinkService.SharePayload payload) {
		return """
			<!doctype html><html><head><meta charset="utf-8"><title>%s</title>
			<style>body{font-family:system-ui,sans-serif;margin:24px;background:#0f1117;color:#e8eaed}
			pre{background:#171923;padding:12px;border-radius:8px;overflow:auto;white-space:pre-wrap}</style></head><body>
			<h1>%s</h1><p><code>%s %s</code></p>
			<h2>Response %d</h2><pre>%s</pre></body></html>
			""".formatted(
			escape(payload.requestName()),
			escape(payload.requestName()),
			escape(payload.method()),
			escape(payload.url()),
			payload.status(),
			escape(payload.responseBody()));
	}

	public record DeployResult(boolean ok, String url, String path, String name) {
	}

	public record PublishResult(boolean ok, String publicUrl, String path, String embedHtml) {
	}

	public record EmbedResult(String html, String script) {
	}

}
